export const NAV_ITEMS = [
  { id: "dashboard", icon: "🏠", label: "Dashboard" },
  { id: "timetable", icon: "📅", label: "Timetable" },
  { id: "plans", icon: "📋", label: "My Plans" },
  { id: "goals", icon: "🎯", label: "Goals" },
  { id: "notes", icon: "📝", label: "Notes" },
  { id: "history", icon: "📊", label: "History" },
  { id: "period", icon: "🌸", label: "Period Tracker" },
  { id: "checklist", icon: "✅", label: "Next Day Prep" },
  { id: "assistant", icon: "🤖", label: "AI Assistant" },
];

export const MOOD_OPTIONS = [
  { emoji: "😊", label: "Happy", value: "happy" },
  { emoji: "😐", label: "Neutral", value: "neutral" },
  { emoji: "😔", label: "Low", value: "low" },
  { emoji: "😤", label: "Stressed", value: "stressed" },
  { emoji: "🤩", label: "Excited", value: "excited" },
  { emoji: "😴", label: "Tired", value: "tired" },
  { emoji: "🤒", label: "Sick", value: "sick" },
  { emoji: "💫", label: "Period", value: "period" },
];

export const DEFAULT_SCHEDULE = {
  Sunday: [
    { time: "06:00", task: "Wake up, warm water, almonds", category: "health" },
    { time: "06:30", task: "Recovery walk + stretching + meditation", category: "health" },
    { time: "07:30", task: "Bath + face pack + skincare", category: "selfcare" },
    { time: "08:30", task: "Breakfast: Poha + curd", category: "meal" },
    { time: "09:00", task: "Weekly review and planning", category: "selfcare" },
    { time: "10:00", task: "Study: AI/ML or Full Stack", category: "study" },
    { time: "12:00", task: "Cooking: Meal prep for the week", category: "study" },
    { time: "13:00", task: "Lunch + medicines", category: "meal" },
    { time: "16:30", task: "Grocery list + prep for Monday", category: "rest" },
    { time: "19:00", task: "Job apply + resume + revise notes", category: "study" },
    { time: "20:30", task: "Night skincare + body oil", category: "selfcare" },
    { time: "23:00", task: "Sleep", category: "rest" },
  ],
  Monday: [
    { time: "05:30", task: "Wake up, prayer, warm water + lemon", category: "health" },
    { time: "05:45", task: "Pre-workout medicine + mobility", category: "health" },
    { time: "06:10", task: "Leave home to park", category: "rest" },
    { time: "06:30", task: "Run + legs, glutes, core workout", category: "health" },
    { time: "08:35", task: "Bath + body care + sunscreen", category: "selfcare" },
    { time: "09:20", task: "Cook breakfast + pack lunch + room reset", category: "rest" },
    { time: "09:55", task: "Breakfast: Moong chilla + curd", category: "meal" },
    { time: "10:45", task: "Office settle + coffee + medicines", category: "work" },
    { time: "13:00", task: "Lunch + medicines", category: "meal" },
    { time: "17:00", task: "Coffee or nimbu pani + healthy snack", category: "meal" },
    { time: "21:35", task: "Study: Job apply / Resume update", category: "study" },
    { time: "22:50", task: "Medicines + night skincare", category: "selfcare" },
  ],
  Tuesday: [
    { time: "05:30", task: "Wake up, prayer, warm water + lemon", category: "health" },
    { time: "06:30", task: "Run + upper body + abs workout", category: "health" },
    { time: "08:35", task: "Full bath + face skincare + sunscreen", category: "selfcare" },
    { time: "09:55", task: "Breakfast: Vegetable oats + paneer", category: "meal" },
    { time: "10:45", task: "Office settle + coffee + dry fruits", category: "work" },
    { time: "13:00", task: "Lunch: dal + sabzi + curd", category: "meal" },
    { time: "13:45", task: "20 min walk + read notes", category: "health" },
    { time: "20:15", task: "Dinner: Paneer/tofu bhurji + salad", category: "meal" },
    { time: "21:35", task: "Study: Job apply / Resume update", category: "study" },
    { time: "22:50", task: "Medicines + night skincare", category: "selfcare" },
  ],
  Wednesday: [
    { time: "05:30", task: "Wake up, prayer, warm water + lemon", category: "health" },
    { time: "06:30", task: "Intervals + yoga/mobility + light core", category: "health" },
    { time: "08:25", task: "Skincare add-on: tomato + curd pack", category: "selfcare" },
    { time: "09:55", task: "Breakfast: Daliya + curd", category: "meal" },
    { time: "10:45", task: "Office settle + coffee + medicines", category: "work" },
    { time: "13:45", task: "20 min walk + read notes", category: "health" },
    { time: "20:15", task: "Dinner: Vegetable soup + sprouts", category: "meal" },
    { time: "21:35", task: "Study: Personal project / Website work", category: "study" },
    { time: "22:50", task: "Medicines + night skincare", category: "selfcare" },
  ],
  Thursday: [
    { time: "05:30", task: "Wake up, prayer, warm water + lemon", category: "health" },
    { time: "06:30", task: "Run + core/belly + stairs", category: "health" },
    { time: "08:25", task: "Skincare add-on: gentle face scrub", category: "selfcare" },
    { time: "09:55", task: "Breakfast: Besan chilla + salad", category: "meal" },
    { time: "10:45", task: "Office settle + coffee + medicines", category: "work" },
    { time: "13:00", task: "Lunch + medicines", category: "meal" },
    { time: "20:15", task: "Dinner: Khichdi + curd", category: "meal" },
    { time: "21:35", task: "Study: DSA + govt prep", category: "study" },
    { time: "22:50", task: "Medicines + night skincare", category: "selfcare" },
  ],
  Friday: [
    { time: "05:30", task: "Wake up, prayer, warm water + lemon", category: "health" },
    { time: "06:30", task: "Run + full body circuit + fun cardio", category: "health" },
    { time: "08:35", task: "Full bath + body care + sunscreen", category: "selfcare" },
    { time: "09:55", task: "Breakfast: Curd + chia/flax + fruit", category: "meal" },
    { time: "10:45", task: "Office settle + coffee + dry fruits", category: "work" },
    { time: "13:00", task: "Lunch + medicines", category: "meal" },
    { time: "20:15", task: "Dinner: Stir-fry veggies + tofu/paneer", category: "meal" },
    { time: "21:35", task: "Study: Portfolio + applications", category: "study" },
    { time: "23:20", task: "Meditation + sleep early", category: "rest" },
  ],
  Saturday: [
    { time: "05:30", task: "Wake up, warm water + almonds + walnuts", category: "health" },
    { time: "05:45", task: "Pre-workout medicine + mobility", category: "health" },
    { time: "06:10", task: "Leave home to park", category: "rest" },
    { time: "06:30", task: "Park: Fun cardio + full-body stretch", category: "health" },
    { time: "08:00", task: "Leave park to home", category: "rest" },
    { time: "08:30", task: "Bath + body oil + face skincare + sunscreen", category: "selfcare" },
    { time: "09:00", task: "Breakfast: Sprouts chaat + fruit", category: "meal" },
    { time: "09:30", task: "Room clean + soak chana for cooking", category: "rest" },
    { time: "10:30", task: "Deep study: DSA + coding", category: "study" },
    { time: "12:30", task: "Cooking practice: try new recipe", category: "study" },
    { time: "13:30", task: "Lunch: Chole/rajma + salad + medicines", category: "meal" },
    { time: "14:30", task: "Skincare: deep treatment + hair oil", category: "selfcare" },
    { time: "15:30", task: "Hobby / creative time", category: "rest" },
    { time: "16:30", task: "Snack: makhana/roasted chana + tea", category: "meal" },
    { time: "17:00", task: "Study: New tools / online course", category: "study" },
    { time: "18:30", task: "Evening walk / cycling / outdoor", category: "health" },
    { time: "19:30", task: "Cook dinner + eat earlier", category: "meal" },
    { time: "20:30", task: "Night skincare + stretch mark care", category: "selfcare" },
    { time: "21:00", task: "Medicines + movie / relaxation", category: "rest" },
    { time: "23:00", task: "Sleep", category: "rest" },
  ],
};

export const DEFAULT_GOALS = [
  {
    id: "weight_loss",
    title: "Weight Loss",
    icon: "⚖️",
    color: "health",
    items: ["80kg to 72-74kg", "8,000-10,000 steps/day", "Protein 60-80g/day", "Weigh every Sunday"],
  },
  {
    id: "skincare",
    title: "Skin + Body Care",
    icon: "✨",
    color: "skin",
    items: ["Sunscreen daily", "Underarm care twice a week", "Stretch marks oil daily", "No harsh scrubs daily"],
  },
  {
    id: "fitness",
    title: "Fitness & Stamina",
    icon: "💪",
    color: "fitness",
    items: ["Run 20-30 min", "Strength all body parts", "Learn yoga/cycling/swimming", "Medicines 3x/day"],
  },
  {
    id: "study",
    title: "Study & Career",
    icon: "📚",
    color: "study",
    items: ["DSA daily", "Sky Scanner clone", "AI/ML course", "Resume + LinkedIn"],
  },
  {
    id: "cooking",
    title: "Cooking",
    icon: "🍳",
    color: "cooking",
    items: ["Healthy weight-loss food", "Master paneer recipes", "Breakfast options", "New recipe weekly"],
  },
];

export const DEFAULT_NOTES = {
  weekly_grocery: [
    "Curd, paneer, milk",
    "Sabzi: palak, lauki, tori, bhindi",
    "Fruits: apple, guava, papaya, banana",
    "Dal, chana, rajma, moong",
    "Sunscreen, body oil, aloe gel",
  ],
  medicine_schedule: [
    "Set 1: pre-workout medicines",
    "Set 2: after lunch medicines",
    "Set 3: night medicines",
    "Carry small pill case to office",
  ],
  meal_ideas: [
    "Breakfast: poha, oats, chilla, daliya, sprouts",
    "Lunch: dal + sabzi + roti + salad + curd",
    "Dinner: paneer bhurji, soup, khichdi, stir-fry",
  ],
  pending_tasks: [
    "HDFC card activate",
    "Running jersey fix",
    "Office charger buy",
    "Resume update on LinkedIn",
  ],
};

export const WORKOUT_PLANS = [
  { title: "Monday - Legs + Glutes + Core", items: ["Run 20-30 min", "Squats", "Lunges", "Glute bridges", "Plank"] },
  { title: "Tuesday - Upper Body + Abs", items: ["Run 20-30 min", "Push-ups", "Rows", "Shoulder press", "Planks"] },
  { title: "Wednesday - Intervals + Yoga", items: ["400m x5", "Yoga/mobility", "Light core"] },
  { title: "Saturday - Fun Cardio", items: ["Badminton", "Dance", "Swimming", "Full-body stretch"] },
];

export const COOKING_PLANS = [
  { title: "Quick Prep Day", items: ["Oats", "Poha", "Dal + sabzi", "Paneer bhurji"] },
  { title: "Protein Focus", items: ["Moong chilla", "Curd bowl", "Dal + sabzi", "Tofu/paneer dinner"] },
  { title: "Comfort Bowl", items: ["Daliya", "Khichdi", "Soup", "Sprouts"] },
  { title: "Weekend Learning", items: ["Rajma", "Chole", "Kadhi", "Paneer tikka"] },
];

export const SKINCARE_WEEKLY = [
  { day: "Mon", routine: "Besan + milk pack, sunscreen, night oil" },
  { day: "Tue", routine: "Face wash + scrub, niacinamide, aloe" },
  { day: "Wed", routine: "Tomato + curd pack, sunscreen, Vit E" },
  { day: "Thu", routine: "Gentle fruit scrub, lactic acid, aloe" },
  { day: "Fri", routine: "Basic skincare, niacinamide, body oil" },
  { day: "Sat", routine: "Coffee milk cleanse, deep body care" },
  { day: "Sun", routine: "Besan + curd, hair oil, weekly reset" },
];

export const TASK_REQUIREMENTS = {
  chilla: ["Moong dal or besan", "Curd", "Chutney"],
  oats: ["Oats", "Milk or water", "Fruit"],
  daliya: ["Daliya", "Vegetables", "Curd"],
  sprouts: ["Soaked sprouts", "Fruit", "Chaat masala"],
  paneer: ["Paneer", "Onion", "Tomato", "Spices"],
  khichdi: ["Rice", "Moong dal", "Curd"],
  chole: ["Chickpeas soaked", "Chole masala"],
  rajma: ["Rajma soaked", "Rice", "Spices"],
  sunscreen: ["Sunscreen SPF 30+"],
  medicine: ["Medicine set", "Pill case"],
  chana: ["Soaked chana", "Dry fruits"],
};

