PHONE_COUNTRIES: list[dict[str, str]] = [
    {"code": "AF", "name": "Afghanistan", "dialCode": "+93"},
    {"code": "AL", "name": "Albania", "dialCode": "+355"},
    {"code": "DZ", "name": "Algeria", "dialCode": "+213"},
    {"code": "AR", "name": "Argentina", "dialCode": "+54"},
    {"code": "AM", "name": "Armenia", "dialCode": "+374"},
    {"code": "AU", "name": "Australia", "dialCode": "+61"},
    {"code": "AT", "name": "Austria", "dialCode": "+43"},
    {"code": "AZ", "name": "Azerbaijan", "dialCode": "+994"},
    {"code": "BH", "name": "Bahrain", "dialCode": "+973"},
    {"code": "BD", "name": "Bangladesh", "dialCode": "+880"},
    {"code": "BY", "name": "Belarus", "dialCode": "+375"},
    {"code": "BE", "name": "Belgium", "dialCode": "+32"},
    {"code": "BO", "name": "Bolivia", "dialCode": "+591"},
    {"code": "BA", "name": "Bosnia & Herzegovina", "dialCode": "+387"},
    {"code": "BR", "name": "Brazil", "dialCode": "+55"},
    {"code": "BG", "name": "Bulgaria", "dialCode": "+359"},
    {"code": "KH", "name": "Cambodia", "dialCode": "+855"},
    {"code": "CM", "name": "Cameroon", "dialCode": "+237"},
    {"code": "CA", "name": "Canada", "dialCode": "+1"},
    {"code": "CL", "name": "Chile", "dialCode": "+56"},
    {"code": "CN", "name": "China", "dialCode": "+86"},
    {"code": "CO", "name": "Colombia", "dialCode": "+57"},
    {"code": "CR", "name": "Costa Rica", "dialCode": "+506"},
    {"code": "HR", "name": "Croatia", "dialCode": "+385"},
    {"code": "CY", "name": "Cyprus", "dialCode": "+357"},
    {"code": "CZ", "name": "Czech Republic", "dialCode": "+420"},
    {"code": "DK", "name": "Denmark", "dialCode": "+45"},
    {"code": "DO", "name": "Dominican Republic", "dialCode": "+1"},
    {"code": "EC", "name": "Ecuador", "dialCode": "+593"},
    {"code": "EG", "name": "Egypt", "dialCode": "+20"},
    {"code": "SV", "name": "El Salvador", "dialCode": "+503"},
    {"code": "EE", "name": "Estonia", "dialCode": "+372"},
    {"code": "ET", "name": "Ethiopia", "dialCode": "+251"},
    {"code": "FI", "name": "Finland", "dialCode": "+358"},
    {"code": "FR", "name": "France", "dialCode": "+33"},
    {"code": "GE", "name": "Georgia", "dialCode": "+995"},
    {"code": "DE", "name": "Germany", "dialCode": "+49"},
    {"code": "GH", "name": "Ghana", "dialCode": "+233"},
    {"code": "GR", "name": "Greece", "dialCode": "+30"},
    {"code": "GT", "name": "Guatemala", "dialCode": "+502"},
    {"code": "HN", "name": "Honduras", "dialCode": "+504"},
    {"code": "HK", "name": "Hong Kong", "dialCode": "+852"},
    {"code": "HU", "name": "Hungary", "dialCode": "+36"},
    {"code": "IS", "name": "Iceland", "dialCode": "+354"},
    {"code": "IN", "name": "India", "dialCode": "+91"},
    {"code": "ID", "name": "Indonesia", "dialCode": "+62"},
    {"code": "IR", "name": "Iran", "dialCode": "+98"},
    {"code": "IQ", "name": "Iraq", "dialCode": "+964"},
    {"code": "IE", "name": "Ireland", "dialCode": "+353"},
    {"code": "IL", "name": "Israel", "dialCode": "+972"},
    {"code": "IT", "name": "Italy", "dialCode": "+39"},
    {"code": "JM", "name": "Jamaica", "dialCode": "+1"},
    {"code": "JP", "name": "Japan", "dialCode": "+81"},
    {"code": "JO", "name": "Jordan", "dialCode": "+962"},
    {"code": "KZ", "name": "Kazakhstan", "dialCode": "+7"},
    {"code": "KE", "name": "Kenya", "dialCode": "+254"},
    {"code": "KW", "name": "Kuwait", "dialCode": "+965"},
    {"code": "KG", "name": "Kyrgyzstan", "dialCode": "+996"},
    {"code": "LV", "name": "Latvia", "dialCode": "+371"},
    {"code": "LB", "name": "Lebanon", "dialCode": "+961"},
    {"code": "LY", "name": "Libya", "dialCode": "+218"},
    {"code": "LT", "name": "Lithuania", "dialCode": "+370"},
    {"code": "LU", "name": "Luxembourg", "dialCode": "+352"},
    {"code": "MO", "name": "Macao", "dialCode": "+853"},
    {"code": "MK", "name": "North Macedonia", "dialCode": "+389"},
    {"code": "MY", "name": "Malaysia", "dialCode": "+60"},
    {"code": "MV", "name": "Maldives", "dialCode": "+960"},
    {"code": "MX", "name": "Mexico", "dialCode": "+52"},
    {"code": "MD", "name": "Moldova", "dialCode": "+373"},
    {"code": "MN", "name": "Mongolia", "dialCode": "+976"},
    {"code": "ME", "name": "Montenegro", "dialCode": "+382"},
    {"code": "MA", "name": "Morocco", "dialCode": "+212"},
    {"code": "MM", "name": "Myanmar", "dialCode": "+95"},
    {"code": "NP", "name": "Nepal", "dialCode": "+977"},
    {"code": "NL", "name": "Netherlands", "dialCode": "+31"},
    {"code": "NZ", "name": "New Zealand", "dialCode": "+64"},
    {"code": "NG", "name": "Nigeria", "dialCode": "+234"},
    {"code": "NO", "name": "Norway", "dialCode": "+47"},
    {"code": "OM", "name": "Oman", "dialCode": "+968"},
    {"code": "PK", "name": "Pakistan", "dialCode": "+92"},
    {"code": "PA", "name": "Panama", "dialCode": "+507"},
    {"code": "PY", "name": "Paraguay", "dialCode": "+595"},
    {"code": "PE", "name": "Peru", "dialCode": "+51"},
    {"code": "PH", "name": "Philippines", "dialCode": "+63"},
    {"code": "PL", "name": "Poland", "dialCode": "+48"},
    {"code": "PT", "name": "Portugal", "dialCode": "+351"},
    {"code": "QA", "name": "Qatar", "dialCode": "+974"},
    {"code": "RO", "name": "Romania", "dialCode": "+40"},
    {"code": "RU", "name": "Russia", "dialCode": "+7"},
    {"code": "SA", "name": "Saudi Arabia", "dialCode": "+966"},
    {"code": "RS", "name": "Serbia", "dialCode": "+381"},
    {"code": "SG", "name": "Singapore", "dialCode": "+65"},
    {"code": "SK", "name": "Slovakia", "dialCode": "+421"},
    {"code": "SI", "name": "Slovenia", "dialCode": "+386"},
    {"code": "ZA", "name": "South Africa", "dialCode": "+27"},
    {"code": "KR", "name": "South Korea", "dialCode": "+82"},
    {"code": "ES", "name": "Spain", "dialCode": "+34"},
    {"code": "LK", "name": "Sri Lanka", "dialCode": "+94"},
    {"code": "SE", "name": "Sweden", "dialCode": "+46"},
    {"code": "CH", "name": "Switzerland", "dialCode": "+41"},
    {"code": "TW", "name": "Taiwan", "dialCode": "+886"},
    {"code": "TJ", "name": "Tajikistan", "dialCode": "+992"},
    {"code": "TZ", "name": "Tanzania", "dialCode": "+255"},
    {"code": "TH", "name": "Thailand", "dialCode": "+66"},
    {"code": "TN", "name": "Tunisia", "dialCode": "+216"},
    {"code": "TR", "name": "Turkey", "dialCode": "+90"},
    {"code": "TM", "name": "Turkmenistan", "dialCode": "+993"},
    {"code": "UG", "name": "Uganda", "dialCode": "+256"},
    {"code": "UA", "name": "Ukraine", "dialCode": "+380"},
    {"code": "AE", "name": "United Arab Emirates", "dialCode": "+971"},
    {"code": "GB", "name": "United Kingdom", "dialCode": "+44"},
    {"code": "US", "name": "United States", "dialCode": "+1"},
    {"code": "UY", "name": "Uruguay", "dialCode": "+598"},
    {"code": "UZ", "name": "Uzbekistan", "dialCode": "+998"},
    {"code": "VE", "name": "Venezuela", "dialCode": "+58"},
    {"code": "VN", "name": "Vietnam", "dialCode": "+84"},
    {"code": "YE", "name": "Yemen", "dialCode": "+967"},
    {"code": "ZM", "name": "Zambia", "dialCode": "+260"},
    {"code": "ZW", "name": "Zimbabwe", "dialCode": "+263"},
]

DEFAULT_PHONE_COUNTRY_CODE = "IN"

